export {default as Navbar } from './navbar/Navbar';
export {default as Footer} from './footer/Footer';
export {default as Hero} from './homepage/Hero';
export {default as HomeTalent} from "./homepage/Talents"
export {default as HomeProjects} from "./homepage/Projects"
export {default as HomeWelcome} from "./homepage/Welcome"
export {default as HomeReviews } from "./homepage/Reviews"
export {default as HomeHowToUse} from "./homepage/HowToUse"
export {default as HomeTopOffers} from "./homepage/TopOffers"
export {default as HomeTestimonial} from './homepage/Testimonial'
export {default as HomeCategories} from './homepage/Categories'
export {default as ProjectCard} from "./homepage/ProjectCard"
export {default as AuthLayoutSider} from "./auth/AuthLayoutSider"
export {default as Category} from "./auth/Category"
export {default as JobProfile} from "./auth/JobProfile"
export {default as TalentDetails} from "./auth/TalentDetails"
export {default as Verification} from './auth/Verification'
export {default as LinkSocials} from './auth/LinkSocials'
export {default as ResetForm} from './auth/ResetForm'
export {default as NewPassword} from './auth/NewPassword'
export {default as ResetOTP} from './auth/ResetOTP'
export {default as ResetDone} from './auth/ResetDone'
export {default as TalentFeedNavbar} from "./talentFeed/TalentFeedNavbar"
export {default as TalentFeedFooter} from './talentFeed/TalentFeedFooter'
export {default as NewPost} from "./talentFeed/NewPost"
export {default as UserCard} from "./talentFeed/UserCard"
export {default as UserProjects} from "./talentFeed/UserProjects"
export {default as UserSkills} from "./talentFeed/UserSkills"
export {default as UserTools} from "./talentFeed/UserTools"
export {default as UserExperience} from "./talentFeed/UserExperience"
export {default as UserPosts} from "./talentFeed/UserPosts"
export {default as Links} from "./talentFeed/Links"
export {default as JobCard} from "./jobs/JobCard"